"""Deterministic Cypher emitter.

Produces ``skills/.graph/skills.cypher`` — a checked-in build artifact
that the runtime ``skillogy.server`` loads on boot. Determinism is the
load-bearing property: the same inputs must always produce a
byte-identical output, otherwise the CI build-and-compare gate doesn't
work.

Determinism rules
-----------------
1. Nodes are emitted sorted by ``(label, key)``.
2. Edges are emitted sorted by ``(from_label, from_key, edge_type, to_label, to_key)``.
3. Properties on a node or edge are emitted in lexicographic key order.
4. List-valued properties keep their author-provided order — they are
   data, not display order — but lists are themselves serialised
   deterministically.
5. Float properties are emitted via ``repr`` so 0.1 → "0.1", not
   "0.10000000000000001". Embeddings are large lists so they are
   emitted on one line to keep the file diff-friendly.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from decepticon.skillogy.builder.model import Edge, Node


def _escape_string(value: str) -> str:
    """Cypher-escape a string literal.

    Escapes backslashes, single quotes, and control characters
    (``\\n`` / ``\\r`` / ``\\t``) so every emitted literal sits on a
    single line. Without this the downstream bulk ingest path
    (``Neo4jBackend.bulk_ingest_cypher``, which splits on ``;\\n``)
    fragments any skill body that contains a literal newline.
    """
    return (
        "'"
        + value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        + "'"
    )


def cypher_literal(value: Any) -> str:
    """Serialise a Python value as a Cypher literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        # Order matters: bool is a subclass of int.
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return _escape_string(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(cypher_literal(v) for v in value) + "]"
    if isinstance(value, dict):
        inner = ", ".join(f"{k}: {cypher_literal(v)}" for k, v in sorted(value.items()))
        return "{" + inner + "}"
    raise TypeError(f"unsupported Cypher literal type: {type(value).__name__}")


def _node_merge(node: Node) -> str:
    """Render a single MERGE statement for a node.

    Properties other than the key are emitted via SET so re-running the
    build against an existing graph idempotently updates them.
    """
    key_lit = cypher_literal(node.properties[node.key_field])
    head = f"MERGE (n:{node.label} {{{node.key_field}: {key_lit}}})"
    extra_props = {k: v for k, v in node.properties.items() if k != node.key_field}
    if not extra_props:
        return head + ";"
    set_clause = ", ".join(f"n.{k} = {cypher_literal(v)}" for k, v in sorted(extra_props.items()))
    return f"{head}\nSET {set_clause};"


def _edge_merge(edge: Edge) -> str:
    """Render a single MERGE statement for an edge."""
    from_lit = cypher_literal(edge.from_key)
    to_lit = cypher_literal(edge.to_key)
    head = (
        f"MATCH (a:{edge.from_label} {{{edge.from_key_field}: {from_lit}}}), "
        f"(b:{edge.to_label} {{{edge.to_key_field}: {to_lit}}})\n"
        f"MERGE (a)-[r:{edge.edge_type}]->(b)"
    )
    if not edge.properties:
        return head + ";"
    set_clause = ", ".join(
        f"r.{k} = {cypher_literal(v)}" for k, v in sorted(edge.properties.items())
    )
    return f"{head}\nSET {set_clause};"


def _dedup_nodes(nodes: Iterable[Node]) -> list[Node]:
    """Drop duplicate (label, key) nodes, preserving the first occurrence."""
    seen: set[tuple[str, str]] = set()
    out: list[Node] = []
    for n in nodes:
        sk = n.sort_key()
        if sk in seen:
            continue
        seen.add(sk)
        out.append(n)
    return out


def _dedup_edges(edges: Iterable[Edge]) -> list[Edge]:
    seen: set[tuple[str, str, str, str, str]] = set()
    out: list[Edge] = []
    for e in edges:
        sk = e.sort_key()
        if sk in seen:
            continue
        seen.add(sk)
        out.append(e)
    return out


def emit_cypher(nodes: list[Node], edges: list[Edge]) -> str:
    """Render the full deterministic Cypher dump.

    Header → nodes (sorted) → blank line → edges (sorted) → trailing newline.
    """
    nodes = sorted(_dedup_nodes(nodes), key=Node.sort_key)
    edges = sorted(_dedup_edges(edges), key=Edge.sort_key)

    lines: list[str] = [
        "// AUTOGENERATED by decepticon.skillogy.builder. Do not edit by hand.",
        f"// nodes={len(nodes)} edges={len(edges)}",
        "",
    ]
    if nodes:
        lines.append("// === nodes ===")
        for n in nodes:
            lines.append(_node_merge(n))
        lines.append("")
    if edges:
        lines.append("// === edges ===")
        for e in edges:
            lines.append(_edge_merge(e))
        lines.append("")
    return "\n".join(lines)
